default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: portfolio_backend_development
  username: <%= ENV["DATABASE_USERNAME"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "postgres" %>
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>

test:
  <<: *default
  database: portfolio_backend_test
  username: <%= ENV["DATABASE_USERNAME"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "postgres" %>
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>

production:
  primary: &primary_production
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *primary_production
    database: <%= ENV['CACHE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: <%= ENV['QUEUE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: <%= ENV['CABLE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    migrations_paths: db/cable_migrate
