# PostgreSQL configuration for Rails portfolio backend
# Ensure you have pg gem installed: gem install pg

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "postgres" %>
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>

development:
  <<: *default
  database: portfolio_backend_development

test:
  <<: *default
  database: portfolio_backend_test

production:
  primary: &primary_production
    <<: *default
    database: portfolio_backend_production
    username: <%= ENV["DATABASE_USERNAME"] || "portfolio_backend" %>
    password: <%= ENV["PORTFOLIO_BACKEND_DATABASE_PASSWORD"] || "postgres" %>

  cache:
    <<: *primary_production
    database: portfolio_backend_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: portfolio_backend_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: portfolio_backend_production_cable
    migrations_paths: db/cable_migrate
